/*
 * Patients API
 * This is the Patients API. It provides RESTful operations for Patients data.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: merca3@inbox.lv
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.75
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The Patient model module.
 * @module model/Patient
 * @version 1.0.0
 */
export default class Patient {
  /**
   * Constructs a new <code>Patient</code>.
   * @alias module:model/Patient
   * @class
   * @param id {String} 
   * @param patientId {String} 
   * @param patientName {String} 
   * @param dateOfBirth {Date} 
   * @param visitDate {Date} 
   */
  constructor(id, patientId, patientName, dateOfBirth, visitDate) {
    this.id = id;
    this.patientId = patientId;
    this.patientName = patientName;
    this.dateOfBirth = dateOfBirth;
    this.visitDate = visitDate;
  }

  /**
   * Constructs a <code>Patient</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Patient} obj Optional instance to populate.
   * @return {module:model/Patient} The populated <code>Patient</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Patient();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('patient_id'))
        obj.patientId = ApiClient.convertToType(data['patient_id'], 'String');
      if (data.hasOwnProperty('patient_name'))
        obj.patientName = ApiClient.convertToType(data['patient_name'], 'String');
      if (data.hasOwnProperty('gender'))
        obj.gender = ApiClient.convertToType(data['gender'], 'String');
      if (data.hasOwnProperty('date_of_birth'))
        obj.dateOfBirth = ApiClient.convertToType(data['date_of_birth'], 'Date');
      if (data.hasOwnProperty('visit_date'))
        obj.visitDate = ApiClient.convertToType(data['visit_date'], 'Date');
      if (data.hasOwnProperty('symptoms'))
        obj.symptoms = ApiClient.convertToType(data['symptoms'], 'String');
      if (data.hasOwnProperty('diagnosis'))
        obj.diagnosis = ApiClient.convertToType(data['diagnosis'], 'String');
      if (data.hasOwnProperty('medication'))
        obj.medication = ApiClient.convertToType(data['medication'], 'String');
      if (data.hasOwnProperty('dosage'))
        obj.dosage = ApiClient.convertToType(data['dosage'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
Patient.prototype.id = undefined;

/**
 * @member {String} patientId
 */
Patient.prototype.patientId = undefined;

/**
 * @member {String} patientName
 */
Patient.prototype.patientName = undefined;

/**
 * @member {String} gender
 */
Patient.prototype.gender = undefined;

/**
 * @member {Date} dateOfBirth
 */
Patient.prototype.dateOfBirth = undefined;

/**
 * @member {Date} visitDate
 */
Patient.prototype.visitDate = undefined;

/**
 * @member {String} symptoms
 */
Patient.prototype.symptoms = undefined;

/**
 * @member {String} diagnosis
 */
Patient.prototype.diagnosis = undefined;

/**
 * @member {String} medication
 */
Patient.prototype.medication = undefined;

/**
 * @member {String} dosage
 */
Patient.prototype.dosage = undefined;

