/*
 * Patients API
 * This is the Patients API. It provides RESTful operations for Patients data.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: merca3@inbox.lv
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.75
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import Error from '../model/Error';
import Patient from '../model/Patient';

/**
* Default service.
* @module api/DefaultApi
* @version 1.0.0
*/
export default class DefaultApi {

    /**
    * Constructs a new DefaultApi. 
    * @alias module:api/DefaultApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the addPatient operation.
     * @callback moduleapi/DefaultApi~addPatientCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Add a patient
     * Add a patient to the system
     * @param {module:model/Patient} body Patient to add
     * @param {module:api/DefaultApi~addPatientCallback} callback The callback function, accepting three arguments: error, data, response
     */
    addPatient(body, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling addPatient");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;

      return this.apiClient.callApi(
        '/patients', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the deletePatient operation.
     * @callback moduleapi/DefaultApi~deletePatientCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete specific patient data
     * This operation deletes a patient data
     * @param {String} patientId ID of patient to delete
     * @param {module:api/DefaultApi~deletePatientCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deletePatient(patientId, callback) {
      
      let postBody = null;
      // verify the required parameter 'patientId' is set
      if (patientId === undefined || patientId === null) {
        throw new Error("Missing the required parameter 'patientId' when calling deletePatient");
      }

      let pathParams = {
        'patient_id': patientId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;

      return this.apiClient.callApi(
        '/patients/{patient_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the getPatient operation.
     * @callback moduleapi/DefaultApi~getPatientCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Patient{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns specific patient data
     * This operation provides a patient data in JSON
     * @param {String} patientId ID of patient to return
     * @param {module:api/DefaultApi~getPatientCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getPatient(patientId, callback) {
      
      let postBody = null;
      // verify the required parameter 'patientId' is set
      if (patientId === undefined || patientId === null) {
        throw new Error("Missing the required parameter 'patientId' when calling getPatient");
      }

      let pathParams = {
        'patient_id': patientId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json', 'application/xml'];
      let returnType = Patient;

      return this.apiClient.callApi(
        '/patients/{patient_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the getPatients operation.
     * @callback moduleapi/DefaultApi~getPatientsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Patient>{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns data about all patients
     * This operation provides a view of the patients data in JSON
     * @param {module:api/DefaultApi~getPatientsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getPatients(callback) {
      
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Patient];

      return this.apiClient.callApi(
        '/patients', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the updatePatient operation.
     * @callback moduleapi/DefaultApi~updatePatientCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update specific patient data
     * This operation updates a patient data in JSON
     * @param {String} patientId ID of patient to update
     * @param {module:api/DefaultApi~updatePatientCallback} callback The callback function, accepting three arguments: error, data, response
     */
    updatePatient(patientId, callback) {
      
      let postBody = null;
      // verify the required parameter 'patientId' is set
      if (patientId === undefined || patientId === null) {
        throw new Error("Missing the required parameter 'patientId' when calling updatePatient");
      }

      let pathParams = {
        'patient_id': patientId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;

      return this.apiClient.callApi(
        '/patients/{patient_id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}