/*
 * Patients API
 * This is the Patients API. It provides RESTful operations for Patients data.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: merca3@inbox.lv
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.75
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PatientsApi);
  }
}(this, function(expect, PatientsApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Patient', function() {
      beforeEach(function() {
        instance = new PatientsApi.Patient();
      });

      it('should create an instance of Patient', function() {
        // TODO: update the code to test Patient
        expect(instance).to.be.a(PatientsApi.Patient);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property patientId (base name: "patient_id")', function() {
        // TODO: update the code to test the property patientId
        expect(instance).to.have.property('patientId');
        // expect(instance.patientId).to.be(expectedValueLiteral);
      });

      it('should have the property patientName (base name: "patient_name")', function() {
        // TODO: update the code to test the property patientName
        expect(instance).to.have.property('patientName');
        // expect(instance.patientName).to.be(expectedValueLiteral);
      });

      it('should have the property gender (base name: "gender")', function() {
        // TODO: update the code to test the property gender
        expect(instance).to.have.property('gender');
        // expect(instance.gender).to.be(expectedValueLiteral);
      });

      it('should have the property dateOfBirth (base name: "date_of_birth")', function() {
        // TODO: update the code to test the property dateOfBirth
        expect(instance).to.have.property('dateOfBirth');
        // expect(instance.dateOfBirth).to.be(expectedValueLiteral);
      });

      it('should have the property visitDate (base name: "visit_date")', function() {
        // TODO: update the code to test the property visitDate
        expect(instance).to.have.property('visitDate');
        // expect(instance.visitDate).to.be(expectedValueLiteral);
      });

      it('should have the property symptoms (base name: "symptoms")', function() {
        // TODO: update the code to test the property symptoms
        expect(instance).to.have.property('symptoms');
        // expect(instance.symptoms).to.be(expectedValueLiteral);
      });

      it('should have the property diagnosis (base name: "diagnosis")', function() {
        // TODO: update the code to test the property diagnosis
        expect(instance).to.have.property('diagnosis');
        // expect(instance.diagnosis).to.be(expectedValueLiteral);
      });

      it('should have the property medication (base name: "medication")', function() {
        // TODO: update the code to test the property medication
        expect(instance).to.have.property('medication');
        // expect(instance.medication).to.be(expectedValueLiteral);
      });

      it('should have the property dosage (base name: "dosage")', function() {
        // TODO: update the code to test the property dosage
        expect(instance).to.have.property('dosage');
        // expect(instance.dosage).to.be(expectedValueLiteral);
      });

    });
  });

}));
