/*
 * Patients API
 * This is the Patients API. It provides RESTful operations for Patients data.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: merca3@inbox.lv
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.75
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PatientsApi);
  }
}(this, function(expect, PatientsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PatientsApi.DefaultApi();
  });

  describe('(package)', function() {
    describe('DefaultApi', function() {
      describe('addPatient', function() {
        it('should call addPatient successfully', function(done) {
          // TODO: uncomment, update parameter values for addPatient call
          /*

          instance.addPatient(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deletePatient', function() {
        it('should call deletePatient successfully', function(done) {
          // TODO: uncomment, update parameter values for deletePatient call
          /*

          instance.deletePatient(patientId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getPatient', function() {
        it('should call getPatient successfully', function(done) {
          // TODO: uncomment, update parameter values for getPatient call and complete the assertions
          /*

          instance.getPatient(patientId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(PatientsApi.Patient);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getPatients', function() {
        it('should call getPatients successfully', function(done) {
          // TODO: uncomment getPatients call and complete the assertions
          /*

          instance.getPatients(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(PatientsApi.Patient);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updatePatient', function() {
        it('should call updatePatient successfully', function(done) {
          // TODO: uncomment, update parameter values for updatePatient call
          /*

          instance.updatePatient(patientId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
